### PR TITLE
Fix Transition passes through all props to children in production build

### LINKED ISSUE #107: Transition passes through all props except component in production
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Because you are using [babel-plugin-transform-react-remove-prop-types](https://github.com/reactjs/react-transition-group/blob/master/.babelrc#L13), in production, [this line of `Transition`](https://github.com/reactjs/react-transition-group/blob/master/src/Transition.js#L270) does not delete anything from the props that it passes through:
```js
Object.keys(Transition.propTypes).forEach(key => delete childProps[key]);
```

**What is the expected behavior?**
`Transition` passes through the same set of props in production as it does in dev mode.

### PR DESCRIPTION
**Pull request by koba04**
Fix #107

### CODE REVIEW

File: src/Transition.js [hunk 1]
```diff
@@ -303,7 +438,7 @@ class Transition extends React.Component {
     }
 
     const {children, ...childProps} = this.props;
-    Object.keys(Transition.propTypes).forEach(key => delete childProps[key]);
+    Object.keys(propTypes).forEach(key => delete childProps[key]);
```
Comment (jquense) [inline src/Transition.js]: lets do `delete props.foo` for each one manually instead, its a bit uglier but maintains the optimization

**Comment by koba04** [comment]
@jquense Thanks! I've changed to delete the props manually and added a test for this.

**Comment by koba04** [comment]
Thanks!
